language: perl
perl:
  - "5.18"

before_script:
  - cpanm --quiet --notest --skip-satisfied https://github.com/codecov/codecov-perl.git

script:
  - perl Build.PL
  - ./Build build
  - cover -test

after_success:
  - cover -report codecov

notifications:
  slack:
    - secure: "AVm7agcHmWTETBTlYd8M3qiU9oWuzFER/+XKVEQHBGuwShnxw1CIcaQYYRSNLrGnxTxFAVMVJEc0ueBaVzaXw2qEPwu4Mcse+EE5S+c/08R2FYQVaaDxGageCdMlWrZZFEJpj/MNeTB4Np8FuChQNwr+UTu9Eyogvwe2WiayzxOTNg+R45KjFjCjnyuZk2KxaZTHmWbzyBZEgtm1FnHZs8wxevd6cwp+v4AauPWjFEbHgeTVNzLoWSFs9NzcHDXAp9Jjf+rEaHh+OIcJRpLVtbUUoaQkNJZqiowKu3J3xXubMsA+9lrB0RmxReOrIeT+Fj2NKxywoh2ZOvUgroe5qFG0vP5oj6lpvUC5maRMtL5QbnWBf/HbaDRX7ayHRZJRASxhjnRwZoURNSazl6Wv2RMMpZUK5J5PKyMQKm5RS/VRCqosDnQSvLDzSi1o8tGV2XHnRFFP5JWnkn8b5AAmAax3LX6Hj0BYFrAvdZNkNawzCRYdNGlnuO+EGE0KNcIkC//RyhzvFAlzHuPdN1SoBjMBPm42CeLsDK9BWnYjF8nuA6hO9WgQ6LlJ9pV+/zgdu81ahclXRLm0Z9OaTG36BctGCc8t/CQ2BR4etryFi6BIz3GoHJ3sJPg12L1pltp7QUSZrEsI5LUeRoiu4z7FUVgNG4BRJL3ECz4GYXpRiOc="

